### PR TITLE
Adding cron style scheduling

### PR DESCRIPTION
**Pull request by Chocrates**
Adds the ability to set cron style scheduling for the background job.

### CODE REVIEW

**Comment by Chocrates** [comment]
I'll get the doc updated before we merge this.  Do you want to allow the previous second based schedule along with Cron or just the new style?

**Comment by primetheus** [comment]
I like the idea of flexibility... how difficult do you think it would be to allow the option? If it's too much we can just stick with `cron` and write up a few examples with a recommended cadence

**Comment by Chocrates** [comment]
ill see what I can figure out.  Shouldn't be too bad, maybe try to parse it as an int and fallback to cron if not

**Comment by primetheus** [comment]
I think it'll be easy to determine the value easily enough... but the scheduling syntax is different... I'm inclined to just leave it with `cron`

**Pull request merged**
